-- MySQL Script generated by MySQL Workbench
-- Tue Dec  3 23:25:46 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Instituicao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Instituicao` (
  `id` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL DEFAULT NULL,
  `CNPJ` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`Familia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Familia` (
  `id` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `endereco` VARCHAR(255) NULL DEFAULT NULL,
  `rendaFamiliar` DECIMAL NULL DEFAULT NULL,
  `representante` VARCHAR(255) NULL DEFAULT NULL,
  `instituicao_id` INT NOT NULL DEFAULT NULL,
  `Instituicao_id` INT NOT NULL,
  PRIMARY KEY (`id`, `instituicao_id`, `Instituicao_id`),
  INDEX `fk_Familia_Instituicao1_idx` (`Instituicao_id` ASC) VISIBLE,
  CONSTRAINT `fk_Familia_Instituicao1`
    FOREIGN KEY (`Instituicao_id`)
    REFERENCES `mydb`.`Instituicao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`Pessoas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pessoas` (
  `CPF` VARCHAR(255) NULL DEFAULT NULL,
  `nome` VARCHAR(255) NULL DEFAULT NULL,
  `telefone` VARCHAR(255) NULL DEFAULT NULL,
  `endereco` VARCHAR(255) NULL DEFAULT NULL,
  `dataNascimento` DATE NULL DEFAULT NULL,
  `familia_id` INT NOT NULL DEFAULT NULL,
  `Familia_id` INT NOT NULL,
  `Familia_instituicao_id` INT NOT NULL,
  `Familia_Instituicao_id` INT NOT NULL,
  PRIMARY KEY (`CPF`, `familia_id`, `Familia_id`, `Familia_instituicao_id`, `Familia_Instituicao_id`),
  INDEX `fk_Pessoas_Familia1_idx` (`Familia_id` ASC, `Familia_instituicao_id` ASC, `Familia_Instituicao_id` ASC) VISIBLE,
  CONSTRAINT `fk_Pessoas_Familia1`
    FOREIGN KEY (`Familia_id` , `Familia_instituicao_id` , `Familia_Instituicao_id`)
    REFERENCES `mydb`.`Familia` (`id` , `instituicao_id` , `Instituicao_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`Parcerias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Parcerias` (
  `CNPJ` VARCHAR(255) NULL DEFAULT NULL,
  `nome` VARCHAR(255) NULL DEFAULT NULL,
  `tipo` VARCHAR(255) NULL DEFAULT NULL,
  `contato` VARCHAR(255) NULL DEFAULT NULL,
  `Instituicao_id` INT NOT NULL,
  `Instituicao_id1` INT NOT NULL,
  PRIMARY KEY (`CNPJ`),
  INDEX `fk_Parcerias_Instituicao_idx` (`Instituicao_id1` ASC) VISIBLE,
  CONSTRAINT `fk_Parcerias_Instituicao`
    FOREIGN KEY (`Instituicao_id1`)
    REFERENCES `mydb`.`Instituicao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`Campanha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Campanha` (
  `id` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL DEFAULT NULL,
  `data` DATE NULL DEFAULT NULL,
  `descricao` TEXT NULL DEFAULT NULL,
  `responsaveis` VARCHAR(255) NULL DEFAULT NULL,
  `instituicao_id` INT NOT NULL,
  `Instituicao_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Campanha_Instituicao1_idx` (`Instituicao_id` ASC) VISIBLE,
  CONSTRAINT `fk_Campanha_Instituicao1`
    FOREIGN KEY (`Instituicao_id`)
    REFERENCES `mydb`.`Instituicao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`Doacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Doacoes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NULL DEFAULT NULL,
  `tipo` VARCHAR(255) NULL DEFAULT NULL,
  `quantValor` DECIMAL NULL DEFAULT NULL,
  `instituicao_id` INT NOT NULL DEFAULT NULL,
  `doador_CPF_CNPJ` VARCHAR(255) NOT NULL,
  `Doacoes_id` INT NOT NULL,
  `Doacoes_doador_CPF_CNPJ` VARCHAR(255) NOT NULL,
  `Doacoes_instituicao_id` INT NOT NULL,
  `Instituicao_id` INT NOT NULL,
  PRIMARY KEY (`id`, `doador_CPF_CNPJ`, `instituicao_id`, `Instituicao_id`),
  INDEX `fk_Doacoes_Instituicao1_idx` (`Instituicao_id` ASC) VISIBLE,
  CONSTRAINT `fk_Doacoes_Instituicao1`
    FOREIGN KEY (`Instituicao_id`)
    REFERENCES `mydb`.`Instituicao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`Doador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Doador` (
  `CPF_CNPJ` VARCHAR(255) NULL DEFAULT NULL,
  `nome` VARCHAR(255) NULL DEFAULT NULL,
  `historicoDoacao` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`CPF_CNPJ`));


-- -----------------------------------------------------
-- Table `mydb`.`Doacoes_has_Doador1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Doacoes_has_Doador1` (
  `Doacoes_id` INT NOT NULL,
  `Doacoes_doador_CPF_CNPJ` VARCHAR(255) NOT NULL,
  `Doacoes_instituicao_id` INT NOT NULL,
  `Doacoes_Instituicao_id` INT NOT NULL,
  `Doador_CPF_CNPJ` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`Doacoes_id`, `Doacoes_doador_CPF_CNPJ`, `Doacoes_instituicao_id`, `Doacoes_Instituicao_id`, `Doador_CPF_CNPJ`),
  INDEX `fk_Doacoes_has_Doador1_Doador1_idx` (`Doador_CPF_CNPJ` ASC) VISIBLE,
  INDEX `fk_Doacoes_has_Doador1_Doacoes1_idx` (`Doacoes_id` ASC, `Doacoes_doador_CPF_CNPJ` ASC, `Doacoes_instituicao_id` ASC, `Doacoes_Instituicao_id` ASC) VISIBLE,
  CONSTRAINT `fk_Doacoes_has_Doador1_Doacoes1`
    FOREIGN KEY (`Doacoes_id` , `Doacoes_doador_CPF_CNPJ` , `Doacoes_instituicao_id` , `Doacoes_Instituicao_id`)
    REFERENCES `mydb`.`Doacoes` (`id` , `doador_CPF_CNPJ` , `instituicao_id` , `Instituicao_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Doacoes_has_Doador1_Doador1`
    FOREIGN KEY (`Doador_CPF_CNPJ`)
    REFERENCES `mydb`.`Doador` (`CPF_CNPJ`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
